--RELATIONAL TABLE DELETION
DROP TABLE R_PENDING;
DROP TABLE R_SUBMISSION;
DROP TABLE R_TAKE;
DROP TABLE R_TEACH;
DROP TABLE R_TUTORING;

--MAIN TABLE DELETION
DROP TABLE STUDENT_FORUM;
DROP TABLE GUARDIAN_FORUM;
DROP TABLE ASSIGNMENT;
DROP TABLE AUTHORITY;
DROP TABLE COURSE;
DROP TABLE DUE_PAYMENT;

DROP TABLE GUARDIAN;
DROP TABLE INSTRUCTOR;
DROP TABLE LECTURE;
DROP TABLE QUESTION_BANK;
DROP TABLE RESOURCES;
DROP TABLE RESULT;
DROP TABLE STUDENT;
DROP TABLE EXAM;